### ISSUE TITLE
Problem with aBSREL

### ISSUE THREAD

**Issue by RobertoFe** [veg/hyphy-absrel#2]
Hi,

I am having a problem to visualise my results of the aBSREL analysis http://test.datamonkey.org/absrel/54ee390e1b6e077b215c1c12 the error I pretty much consistently get is  
Error
unable to read the results file (this is the link to my analysis http://test.datamonkey.org/absrel/54ee390e1b6e077b215c1c12).

Since I am not able to use aBSREL, I have performed my analysis using BSREL on my local machine. After that I have tried to visualise the results (.json file) using http://octamonkey.ucsd.edu/datamonkey-js-ui/aBSREL/ui/bsrel.html without any success. I though it was a problem with the browser but I still get the same error using Mozilla, Chrome and Safari.

Any help would be very appreciate.

Thanks in advance

Roberto

**Comment by stevenweaver** [comment]
Hi Roberto, 

Sorry, aBSREL was just added to datamonkey, and there was a time limit set on our cluster for a processing time of one hour. The job would be killed after processing for more than one hour. 

I've restarted your job and increased the time limit for the job to two days. 
http://test.datamonkey.org/absrel/54ee691d1ee7ddb50661eea6

Thank you,
Steven

**Comment by stevenweaver** [comment]
Hi Roberto, 

If you would still like to use your JSON file, you can use the page located at http://veg.github.io/hyphy-vision/absrel

This page should always have the most up-to-date code.

Thanks,
Steven
